"""add hero image to stores

Revision ID: 06109fecd44c
Revises: e79bfabb4f76
Create Date: 2026-10-06 10:25:05.269997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06109fecd44c'
down_revision: Union[str, Sequence[str], None] = 'e79bfabb4f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('hero_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'hero_image')
    # ### end Alembic commands ###
