"""add benefitpay iban to stores

Revision ID: 80aab516b603
Revises: bd379965bbb2
Create Date: 2026-10-06 14:38:02.371393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80aab516b603'
down_revision: Union[str, Sequence[str], None] = 'bd379965bbb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('benefitpay_iban', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'benefitpay_iban')
    # ### end Alembic commands ###
