"""add show orders to stores

Revision ID: bd379965bbb2
Revises: 06109fecd44c
Create Date: 2026-10-06 14:12:13.010649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd379965bbb2'
down_revision: Union[str, Sequence[str], None] = '06109fecd44c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'stores',
        sa.Column(
            'show_orders',
            sa.Boolean(),
            nullable=False,
            server_default=sa.true()
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'show_orders')
    # ### end Alembic commands ###